#!/bin/bash

# print the number of arguments then a blank line
echo "There are $# arguments"
echo

# print each argument's value, starting with argument 1
declare -i num=1

# note you don't need the [in list] part - assumes $@
for arg
do
	echo "    argument $num is $arg"

	# manipulating numeric variable - inside ((   ))
	(( num++ ))
done

