#!/bin/bash

# put the output of ls in an array
files=`/bin/ls`

# loop that goes through each filename in the directory
for f in ${files[*]}
do
	# ignore myself
	if [[ $f = recursive_listing ]]
	then
		continue

	# plain file
	elif [[ -f $f ]]
	then
		echo "$1$f is a plain file"

	# directory - enter it and recurse
	elif [[ -d $f ]]
	then
		echo "$1entering directory $f"
		cd $f
		
		# recursive call - add spaces for indentation
		~/shell_prog/scripts/recursive_listing "$1    "
		cd ..
	fi
done

